services:
  mongo:
    image: mongo:6.0
    restart: always
    mem_limit: 64gb
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-tools:/tools
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  import:
    build: ./docker
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 32G
    depends_on:
      - mongo
    volumes:
      - ./originalData:/originalData
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - ORIGINAL_DATA_PATH=/originalData
    command: npm run cron

  pubchem:
    build: ./docker
    restart: always
    mem_limit: 32gb
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.octochemdb.rule=Host(`octochemdb.cheminfo.org`)'
      - 'traefik.http.routers.octochemdb.entrypoints=websecure'
      - 'traefik.http.routers.octochemdb.middlewares=octochemdb'
      - 'traefik.http.routers.octochemdb.tls.certresolver=letsencrypt'
      - 'traefik.http.middlewares.octochemdb.headers.accesscontrolalloworiginlist=*'
      - 'traefik.http.middlewares.octochemdb.headers.accesscontrolallowheaders=Content-Type'
      - 'traefik.http.middlewares.octochemdb.headers.accesscontrolmaxage=86400'
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
