version: '2.2'
services:
  mongo:
    image: mongo:4.2
    restart: always
    mem_limit: 30000m
    memswap_limit: 30000m
    volumes:
      - ./mongo-data:/data/db

  node-pubchem-import:
    build: ./node-pubchem
    restart: always
    privileged: true
    depends_on:
      - mongo
    volumes:
      - ./originalData:/git/node-pubchem/originalData
    command: npm run cron

  node-pubchem:
    build: ./node-pubchem
    restart: always
    ports:
      - 127.0.0.1:3001:80
    depends_on:
      - mongo
