services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  import:
    build:
      context: ./docker
    env_file:
      - ./docker/.env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - NODE_ENV=production
    command: npm run cron
    depends_on:
      - mongo
    volumes:
      - original-data:/git/originalData

  server:
    build:
      context: ./docker
    env_file:
      - ./docker/.env
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - NODE_ENV=production
    command: npm run start
    ports:
      - "11015:11015"
    depends_on:
      - mongo

volumes:
  mongo-data:
  original-data:
