version: '2.2'
services:
  mongo:
    image: mongo:5.0
    restart: always
    mem_limit: 30000m
    memswap_limit: 30000m
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-tools:/tools
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    networks:
      - ocl-cache-docker_some-net

  import:
    build: ./pubchem
    restart: always
    privileged: true
    depends_on:
      - mongo
    volumes:
      - ./originalData:/originalData
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - ORIGINAL_DATA_PATH=/originalData
    command: npm run cron
    networks:
      - ocl-cache-docker_some-net

  pubchem:
    build: ./pubchem
    restart: always
    ports:
      - 127.0.0.1:3001:11015
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    networks:
      - ocl-cache-docker_some-net
networks:
  ocl-cache-docker_some-net:
    external: true
