const antiBacterialSet = new Set();

const antiBacterial = [
  ' Agents, Anti-Bacterial',
  'Anti Bacterial Agents',
  'Antibacterial Agents',
  'Agents, Antibacterial',
  'Antibacterial Agent',
  'Agent, Antibacterial',
  'Anti-Bacterial Compounds',
  'Anti Bacterial Compounds',
  'Compounds, Anti-Bacterial',
  'Anti-Bacterial Agent',
  'Agent, Anti-Bacterial',
  'Anti Bacterial Agent',
  'Anti-Bacterial Compound',
  'Anti Bacterial Compound',
  'Compound, Anti-Bacterial',
  'Bacteriocidal Agents',
  'Agents, Bacteriocidal',
  'Bacteriocidal Agent',
  'Agent, Bacteriocidal',
  'Bacteriocide',
  'Bacteriocides',
  'Anti-Mycobacterial Agents',
  'Agents, Anti-Mycobacterial',
  'Anti Mycobacterial Agents',
  'Anti-Mycobacterial Agent',
  'Agent, Anti-Mycobacterial',
  'Anti Mycobacterial Agent',
  'Antimycobacterial Agent',
  'Agent, Antimycobacterial',
  'Antimycobacterial Agents',
  'Agents, Antimycobacterial',
  'Antibiotics',
  'Antibiotic',
  'Agents, Antitreponemal',
  'Antitreponemal Drugs',
  'Drugs, Antitreponemal',
  'Antisyphilitic Agents',
  'Agents, Antisyphilitic',
  'Antisyphilitics',
  'Antisyphilitic Drugs',
  'Drugs, Antisyphilitic',
  'Anti-Tuberculosis Agent',
  'Agent, Anti-Tuberculosis',
  'Anti Tuberculosis Agent',
  'Anti-Tuberculosis Drug',
  'Anti Tuberculosis Drug',
  'Drug, Anti-Tuberculosis',
  'Tuberculostatic Agents',
  'Tuberculostatic Agent',
  'Agent, Tuberculostatic',
  'Anti-Tuberculosis Drugs',
  'Anti Tuberculosis Drugs',
  'Anti-Tuberculosis Agents',
  'Anti Tuberculosis Agents',
  'Antitubercular Drugs',
  'Antitubercular Agent',
  'Agent, Antitubercular',
  'Antitubercular Drug',
  'Drug, Antitubercular',
  'Antitubercular Antibiotics',
  'Agents, Anti-Bacterial',
  'Anti Bacterial Agents',
  'Antibacterial Agents',
  'Agents, Antibacterial',
  'Antibacterial Agent',
  'Agent, Antibacterial',
  'Anti-Bacterial Compounds',
  'Anti Bacterial Compounds',
  'Compounds, Anti-Bacterial',
  'Anti-Bacterial Agent',
  'Agent, Anti-Bacterial',
  'Anti Bacterial Agent',
  'Anti-Bacterial Compound',
  'Anti Bacterial Compound',
  'Compound, Anti-Bacterial',
  'Bacteriocidal Agents',
  'Agents, Bacteriocidal',
  'Bacteriocidal Agent',
  'Agent, Bacteriocidal',
  'Bacteriocide',
  'Bacteriocides',
  'Anti-Mycobacterial Agents',
  'Agents, Anti-Mycobacterial',
  'Anti Mycobacterial Agents',
  'Anti-Mycobacterial Agent',
  'Agent, Anti-Mycobacterial',
  'Anti Mycobacterial Agent',
  'Antimycobacterial Agent',
  'Agent, Antimycobacterial',
  'Antimycobacterial Agents',
  'Agents, Antimycobacterial',
  'Antibiotics',
  'Antibiotic',
  'Agents, Antitreponemal',
  'Antitreponemal Drugs',
  'Drugs, Antitreponemal',
  'Antisyphilitic Agents',
  'Agents, Antisyphilitic',
  'Antisyphilitics',
  'Antisyphilitic Drugs',
  'Drugs, Antisyphilitic',
  'Antitubercular Antibiotics',
  'Inhibitors, beta-Lactamase',
  'beta Lactamase Inhibitor',
  'Inhibitor, beta Lactamase',
  'Lactamase Inhibitor, beta',
  'beta Lactamase Inhibitors',
  'Inhibitors, beta Lactamase',
  'Lactamase Inhibitors, beta',
  'beta Lactamase Antagonists',
  'Antagonists, beta Lactamase',
  'Lactamase Antagonists, beta',
  'beta-Lactamase Inhibitor',
  'Inhibitor, beta-Lactamase',
  'Agents, Leprostatic',
  'Leprostatics',
  'Antileprotic Agents',
  'Agents, Antileprotic',
];
const antiInfectiveUrinarySet = new Set();

const antiInfectiveUrinary = [
  'Anti Infective Agents, Urinary',
  'Urinary Antiinfective Agents',
  'Antiinfective Agents, Urinary',
  'Agents, Urinary Antiinfective',
  'Urinary Anti-Infective Agents',
  'Agents, Urinary Anti-Infective',
  'Urinary Anti Infective Agents',
  'Antiseptics, Urinary',
  'Urinary Antiseptics',
];

const antiFungalSet = new Set();

const antiFungal = [
  'Agents, Antifungal',
  'Therapeutic Fungicides',
  'Fungicides, Therapeutic',
  'Antifungal Agent',
  'Agent, Antifungal',
  'Antibiotics, Antifungal',
  'Antifungal Antibiotics',
];

const antiParasiticSet = new Set();

const antiParasitic = [
  'Agents, Antiparasitic',
  'Antiparasitic Drug',
  'Drug, Antiparasitic',
  'Parasiticide',
  'Parasiticides',
  'Antiparasitic',
  'Antiparasitics',
  'Antiparasitic Drugs',
  'Drugs, Antiparasitic',
  'Antiparasitic Agent',
  'Agent, Antiparasitic',
  'Vermifuge',
  'Vermifuges',
  'Antihelmintics',
  'Anthelmintic',
  'Antihelmintic',
  'Agents, Antinematodal',
  'Nematocides',
  'Antinematodal Drugs',
  'Drugs, Antinematodal',
  'Antinematodals',
  'Agents, Antiplatyhelmintic',
  'Antiplatyhelmintic Drugs',
  'Drugs, Antiplatyhelmintic',
  'Antiplatyhelmintics',
  'Agents, Anticestodal',
  'Scolicidal Agents',
  'Agents, Scolicidal',
  'Scolicides',
  'Taeniacides',
  'Schistosomicide',
  'Antischistosomal Agents',
  'Agents, Antischistosomal',
  'Antischistosomal Agent',
  'Agent, Antischistosomal',
  'Agents, Antiplatyhelmintic',
  'Antiplatyhelmintic Drugs',
  'Drugs, Antiplatyhelmintic',
  'Antiplatyhelmintics',
  'Agents, Antiprotozoal',
  'Schizonticides',
  'Amoebicides',
  'Antimalarial',
  'Anti-Malarial',
  'Anti Malarial',
  'Antimalarial Drugs',
  'Drugs, Antimalarial',
  'Anti-Malarials',
  'Anti Malarials',
  'Antimalarial Agents',
  'Agents, Antimalarial',
  'Antimalarial Drug',
  'Drug, Antimalarial',
  'Antimalarial Agent',
  'Agent, Antimalarial',
  'Agents, Antitrichomonal',
  'Antitrichomonal Drugs',
  'Drugs, Antitrichomonal',
  'Trichomonicides',
  'Antitrichomonals',
  'Anticoccidial Agents',
  'Agents, Anticoccidial',
  'Agents, Trypanocidal',
  'Trypanocidal Drugs',
  'Drugs, Trypanocidal',
  'Trypanosomicides',
  'Trypanocides',
  'Trypanosomicidal Agents',
  'Agents, Trypanosomicidal',
];

const antiViralSet = new Set();

const antiViral = [
  'Agents, Antiviral',
  'Antivirals',
  'Antiviral',
  'Antiviral Drugs',
  'Drugs, Antiviral',
  'Antiviral Drug',
  'Drug, Antiviral',
  'Antiviral Agent',
  'Agent, Antiviral',
  'Agents, Anti-Retroviral',
  'Anti Retroviral Agents',
  'Antiretroviral Agents',
  'Agents, Antiretroviral',
  'Antiretroviral Agent',
  'Agent, Antiretroviral',
  'Agents, Anti-HIV',
  'Anti HIV Agents',
  'AIDS Drug',
  'Drug, AIDS',
  'AIDS Drugs',
  'Drugs, AIDS',
  'Anti-HIV Drugs',
  'Anti HIV Drugs',
  'Drugs, Anti-HIV',
  'Anti-AIDS Drug',
  'Anti AIDS Drug',
  'Drug, Anti-AIDS',
  'Anti-AIDS Agents',
  'Agents, Anti-AIDS',
  'Anti AIDS Agents',
  'Anti-AIDS Drugs',
  'Anti AIDS Drugs',
  'Drugs, Anti-AIDS',
  'Anti-HIV Agent',
  'Agent, Anti-HIV',
  'Anti HIV Agent',
  'Anti-HIV Drug',
  'Anti HIV Drug',
  'Drug, Anti-HIV',
  'Antagonists, CCR5 Receptor',
  'Receptor Antagonists, CCR5',
  'CC Chemokine Receptor 5 Blockers',
  'Chemokine Co-receptor 5 Antagonists',
  'Chemokine Co receptor 5 Antagonists',
  'HIV-1 Fusion Coreceptor Antagonists',
  'HIV 1 Fusion Coreceptor Antagonists',
  'CC Chemokine Receptor 5 Antagonists',
  'CCR5 Receptor Blockers',
  'Blockers, CCR5 Receptor',
  'Receptor Blockers, CCR5',
  'Fusion Inhibitors, HIV',
  'HIV Fusion Protein Inhibitor',
  'HIV Fusion Protein Inhibitors',
  'HIV Cell Fusion Inhibitor',
  'HIV Fusion Inhibitor',
  'Fusion Inhibitor, HIV',
  'Inhibitor, HIV Fusion',
  'HIV Cell Fusion Inhibitors',
  'HIV Entry Inhibitors',
  'Entry Inhibitors, HIV',
  'HIV Entry Inhibitor',
  'Entry Inhibitor, HIV',
  'Inhibitor, HIV Entry',
  'Integrase Inhibitors, HIV',
  'Inhibitors, HIV Integrase',
  'Inhibitors, HIV Protease',
  'Protease Inhibitors, HIV',
  'HIV Protease Inhibitor',
  'Inhibitor, HIV Protease',
  'Protease Inhibitor, HIV',
  'Inhibitors, Reverse Transcriptase',
  'Reverse Transcriptase Inhibitor',
  'Inhibitor, Reverse Transcriptase',
  'Transcriptase Inhibitor, Reverse',
  'Inhibitors, Viral Protease',
  'Protease Inhibitors, Viral',
  'Inhibitor of Viral Protease',
  'Protease Inhibitor, Viral',
  'Viral Protease Inhibitor',
  'Virus Protease Inhibitors',
  'Inhibitors, Virus Protease',
  'Protease Inhibitors, Virus',
];

for (let antiBacteriaWord of antiBacterial) {
  antiBacterialSet.add(antiBacteriaWord);
}

for (let entry of antiInfectiveUrinary) {
  antiInfectiveUrinarySet.add(entry);
}
for (let entry of antiFungal) {
  antiFungalSet.add(entry);
}
for (let entry of antiParasitic) {
  antiParasiticSet.add(entry);
}
for (let entry of antiViral) {
  antiViralSet.add(entry);
}
export function getMeshTermsType(keyword) {
  if (antiBacterialSet.has(keyword)) {
    return 'antiBacterial';
  }
  if (antiInfectiveUrinarySet.has(keyword)) {
    return 'antiInfectiveUrinary';
  }
  if (antiFungalSet.has(keyword)) {
    return 'antiFungal';
  }
  if (antiParasiticSet.has(keyword)) {
    return 'antiParasitic';
  }
  if (antiViralSet.has(keyword)) {
    return 'antiViral';
  }
}
